bars:
  [
    {
      x_ticks: [ '2017','2018','2019','2020','2021','2022'],
      y_data: [ 63,120,168,195,344,1035 ],
      x_label: '年份',
      y_label: '产量/万件',
      title: '2017-2022年中国VR/AR头戴设备市场规模及预测趋势图',
    },

    {
      x_ticks: [ '2017','2018','2019','2020','2021','2022' ],
      y_data: [ 11.1,28.1,65.6,115.2,217.1,356.9 ],
      x_label: '年份',
      y_label: '市场规模/亿元',
      title: '2017-2022年中国VR/AR内容和服务市场规模及预测趋势图',
    }
  ]

barhs:
  [
    {
      x_ticks: ['腾讯','LG','歌尔光学','三星','京东方', '国家电网','微软','脸书','谷歌',],
      y_data:[ 709,526,515,406,402,402,312,275,270],
      x_label: '数量/项',
      title: '2021年9月全球虚拟现实行业专利申请数量统计',
    },
  ]

twinx_bars:
  [
    {
      x_ticks: ['2017','2018','2019','2020','2021', '2022'],
      y1_data:[ 191,120,80,65,99,56],
      y2_data:[ 55.60,64.13,49.03,190.65,109.36,110.61],
      x_label:  '年份',
      y1_label: '投资数量/起',
      y2_label: '投资金额/亿元',
      title: '2017-2022年上半年我国VR/AR行业投资情况统计',
    },
  ]

pies:
  [
    {
      x_data: [ 54.6, 16.0, 8.3, 7.8, 5.4, 4.1, 0.9, 2.9],
      labels: [ '娱乐', '教育', '直播', '房产家居', '医疗健康', '工业制造', '文旅', '其他'],
      title: '中国AR/VR内容市场份额占比统计',
      explode : '(0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.3, 0.1)',
    },

  ]
